from enum import StrEnum


class ErrorCode(StrEnum):

    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_RATE_LIMIT  = "LLM_RATE_LIMIT"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    LLM_AUTHENTICATION_ERROR = "LLM_AUTHENTICATION_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BUSINESS_ERROR = "BUSINESS_ERROR"
    RATE_LIMITER_TIMEOUT = "RATE_LIMITER_TIMEOUT"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"